VertexDeclaration = 
{
	{ 0,  0, "D3DDECLTYPE_FLOAT3", "D3DDECLMETHOD_DEFAULT", "D3DDECLUSAGE_POSITION", 0 },
	{ 0, 12, "D3DDECLTYPE_FLOAT2", "D3DDECLMETHOD_DEFAULT", "D3DDECLUSAGE_TEXCOORD", 0 },
}